# ==============================================================================
# Paling fleet discovery (Traefik file-route installation)
# ==============================================================================
# The paling daemon runs bare-metal (MLX/Metal) and is therefore NOT on the
# docker network, so Traefik's docker provider -- which discovers the sidecar
# container by its labels -- cannot see the daemon. The established fleet pattern
# for routing to a host-side endpoint is Traefik's FILE provider: the fleet
# traefik watches ${PREFIX}/var/traefik/dynamic and hot-reloads any *.yml dropped
# there (delightd writes the same shape for discovered LLMs).
#
# At startup the daemon installs its own route file so it becomes mesh-routable
# at Host(`paling-daemon.local`) without any runtime registration call. The
# operation is idempotent (overwrite-in-place) and best-effort: a missing
# directory or write error must never stop the daemon from serving -- discovery
# is a convenience layer, not a precondition for the bare-metal work.
import logging
import os
from pathlib import Path
from typing import Optional

from pydantic import BaseModel

logger = logging.getLogger(__name__)

# the host the daemon answers on, as seen from inside the traefik container.
# host.docker.internal resolves the bare-metal host from the docker network.
_DEFAULT_DAEMON_UPSTREAM = "http://host.docker.internal:8090"
_DEFAULT_DAEMON_HOST_RULE = "paling-daemon.local"


class RouteInstallResult(BaseModel):
    # json contract returned so a caller/skill can assert what happened.
    installed: bool
    path: str
    rule: str
    message: Optional[str] = None


def _dynamic_dir(prefix: Optional[Path] = None) -> Path:
    # the directory the fleet traefik file-provider watches: ${PREFIX}/var/traefik/
    # dynamic. PREFIX is configurable rather than hardcoded because this software's
    # "var" need not sit under the same root as its code -- code may live in
    # ${HOME}/work while runtime/volatile data lives in ${HOME}/var. resolution
    # order: a full-path override, then the PALING_VAR prefix env, then the prefix
    # arg, then ${HOME} as the default.
    # FOLLOW-UP (not built here): delightd should eventually report the PREFIX (and
    # where this software's "var" lives) so the daemon does not have to assume it.
    override = os.environ.get("PALING_TRAEFIK_DYNAMIC_DIR")
    if override:
        return Path(override).expanduser()
    env_prefix = os.environ.get("PALING_VAR")
    if env_prefix:
        base = Path(env_prefix).expanduser()
    elif prefix:
        base = Path(prefix).expanduser()
    else:
        base = Path.home()
    return base / "var" / "traefik" / "dynamic"


def _render_traefik_dynamic_config(rule: str, upstream: str) -> str:
    # build the traefik file-provider dynamic-config fragment (a router + service
    # pointing traefik at the bare-metal daemon). kept as literal yaml text (no
    # yaml dep) so the daemon's hot path carries no extra import.
    return (
        "# generated by paling daemon at startup -- routes the bare-metal daemon\n"
        "# (off the docker network) through the fleet traefik via the file provider.\n"
        "http:\n"
        "  routers:\n"
        "    paling-daemon:\n"
        f"      rule: \"Host(`{rule}`)\"\n"
        "      entrypoints:\n"
        "        - web\n"
        "      service: paling-daemon\n"
        "  services:\n"
        "    paling-daemon:\n"
        "      loadBalancer:\n"
        "        servers:\n"
        f"          - url: \"{upstream}\"\n"
    )


# install_daemon_route drops the daemon's traefik file-route into the watched
# dynamic-config dir so the fleet traefik starts routing to the bare-metal daemon.
def install_daemon_route(
    prefix: Optional[Path] = None,
    upstream: str = _DEFAULT_DAEMON_UPSTREAM,
    rule: str = _DEFAULT_DAEMON_HOST_RULE,
) -> RouteInstallResult:
    # write ${PREFIX}/var/traefik/dynamic/paling.yml so traefik routes the daemon.
    # best-effort and idempotent: returns a result struct, never raises.
    dyn_dir = _dynamic_dir(prefix)
    target = dyn_dir / "paling.yml"
    try:
        dyn_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(_render_traefik_dynamic_config(rule, upstream))
    except OSError as e:
        logger.warning("traefik route install failed (non-fatal): %s", e)
        return RouteInstallResult(
            installed=False,
            path=str(target),
            rule=rule,
            message=str(e),
        )
    logger.info("installed traefik file-route for daemon at %s", target)
    return RouteInstallResult(installed=True, path=str(target), rule=rule)
