# ==============================================================================
# Paling fleet discovery (Traefik file-route installation)
# ==============================================================================
# The paling daemon runs bare-metal (MLX/Metal) and is therefore NOT on the
# docker network, so Traefik's docker provider -- which discovers the sidecar
# container by its labels -- cannot see the daemon. The established fleet pattern
# for routing to a host-side endpoint is Traefik's FILE provider: the fleet
# traefik watches ~/var/traefik/dynamic and hot-reloads any *.yml dropped there
# (delightd writes the same shape for discovered LLMs).
#
# At startup the daemon installs its own route file so it becomes mesh-routable
# at Host(`paling-daemon.local`) without any runtime registration call. The
# operation is idempotent (overwrite-in-place) and best-effort: a missing
# directory or write error must never stop the daemon from serving -- discovery
# is a convenience layer, not a precondition for the bare-metal work.
import logging
import os
from pathlib import Path
from typing import Optional

from pydantic import BaseModel

logger = logging.getLogger(__name__)

# the host the daemon answers on, as seen from inside the traefik container.
# host.docker.internal resolves the bare-metal host from the docker network.
_DEFAULT_DAEMON_UPSTREAM = "http://host.docker.internal:8090"
_DEFAULT_DAEMON_HOST_RULE = "paling-daemon.local"


class RouteInstallResult(BaseModel):
    # json contract returned so a caller/skill can assert what happened.
    installed: bool
    path: str
    rule: str
    message: Optional[str] = None


def _dynamic_dir(home: Optional[Path] = None) -> Path:
    # the directory the fleet traefik file-provider watches. overridable for
    # tests and for non-default workstation layouts.
    override = os.environ.get("PALING_TRAEFIK_DYNAMIC_DIR")
    if override:
        return Path(override).expanduser()
    base = Path(home).expanduser() if home else Path.home()
    return base / "var" / "traefik" / "dynamic"


def _render(rule: str, upstream: str) -> str:
    # render the traefik file-provider dynamic config. kept as literal yaml text
    # (no yaml dep) so the daemon's hot path carries no extra import.
    return (
        "# generated by paling daemon at startup -- routes the bare-metal daemon\n"
        "# (off the docker network) through the fleet traefik via the file provider.\n"
        "http:\n"
        "  routers:\n"
        "    paling-daemon:\n"
        f"      rule: \"Host(`{rule}`)\"\n"
        "      entrypoints:\n"
        "        - web\n"
        "      service: paling-daemon\n"
        "  services:\n"
        "    paling-daemon:\n"
        "      loadBalancer:\n"
        "        servers:\n"
        f"          - url: \"{upstream}\"\n"
    )


def install_daemon_route(
    home: Optional[Path] = None,
    upstream: str = _DEFAULT_DAEMON_UPSTREAM,
    rule: str = _DEFAULT_DAEMON_HOST_RULE,
) -> RouteInstallResult:
    # write ~/var/traefik/dynamic/paling.yml so traefik routes the daemon.
    # best-effort and idempotent: returns a result struct, never raises.
    dyn_dir = _dynamic_dir(home)
    target = dyn_dir / "paling.yml"
    try:
        dyn_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(_render(rule, upstream))
    except OSError as e:
        logger.warning("traefik route install failed (non-fatal): %s", e)
        return RouteInstallResult(
            installed=False,
            path=str(target),
            rule=rule,
            message=str(e),
        )
    logger.info("installed traefik file-route for daemon at %s", target)
    return RouteInstallResult(installed=True, path=str(target), rule=rule)
