# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: paling/proto/banchan_event.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'paling/proto/banchan_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n paling/proto/banchan_event.proto\x12\rpaling.events\"\x87\x02\n\x0c\x42\x61nchanEvent\x12\x10\n\x08\x62\x65nto_id\x18\x01 \x01(\t\x12\x14\n\x0c\x62\x61nchan_name\x18\x02 \x01(\t\x12\x30\n\x05state\x18\x03 \x01(\x0e\x32!.paling.events.BanchanEvent.State\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x12\n\ntool_event\x18\x05 \x01(\t\x12\x15\n\rerror_message\x18\x06 \x01(\t\"_\n\x05State\x12\x0f\n\x0bNOT_STARTED\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\x0b\n\x07PARTIAL\x10\x02\x12\x11\n\rNEEDS_MASSAGE\x10\x03\x12\x08\n\x04\x44ONE\x10\x04\x12\n\n\x06\x46\x41ILED\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paling.proto.banchan_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BANCHANEVENT']._serialized_start=52
  _globals['_BANCHANEVENT']._serialized_end=315
  _globals['_BANCHANEVENT_STATE']._serialized_start=220
  _globals['_BANCHANEVENT_STATE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
